spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.5/sys?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell

wechat:

  #公众平台,授权
  mpAppId: wxd898fcb01713c658
  mpAppSecret:

  #开放平台,卖家扫码使用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

  #支付/商户号
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  KeyPath: D:\eclipse-11\h5.p12
  notifyUrl: http://sell6.mynatapp.cc/sell/pay/notify

